### PR TITLE
BBOT-982: Update switchToNextTab.js to account for presence or absence of backup tab

### PR DESCRIPTION
**Pull request by manderson-te**

### CODE REVIEW

**Comment by manderson-te** [comment]
/review @jdougherty-te @hashlock-te 
/assign @hashlock-te 

Looks like you folks have the ability to merge PRs in this repo.

**Comment by hashlock** [comment]
@manderson-te - if the backup tab is an internal thing that the user shouldn't have to be aware of, maybe we can handle it automatically and reduce the number of functions? 

```
async function switchToNextTab() {
  const currentTabId = await driver.getWindowHandle();

  // Get all tabs, excluding the TE internal backup tab
  const allTabIds = await driver.getAllWindowHandles();
  const backupTabId = allTabIds.filter(tabId => tabId !== currentTabId)[0];
  const nonBackupTabs = allTabIds.filter(tabId => tabId !== backupTabId);
 
  // Switch to next tab (excluding backup tab)
  const currentTabIndex = nonBackupTabs.findIndex(tabId => tabId === currentTabId);
  const nextTabId = nonBackupTabs[currentTabIndex + 1] || allTabIds[0];
  return driver.switchTo().window(nextTabId);
} 
```

**Comment by manderson-te** [comment]
@hashlock-te unfortunately, the only time we're able to identify the backup tab's ID is before the first call to `driver.get()`.  We won't be able to re-identify the backup tab on subsequent calls to `switchToNextTab()`.  In the future, once we've release the Headless Chromium branch, we'll be able to return to a simple code example.

**Comment by hashlock** [comment]
Got it that makes sense.

**Pull request merged**
